Update Cargo.toml
bindgen 0.53.1 doesn't work on Apple M1, yielding the wonderfully cryptic:

```
thread 'main' panicked at 'libclang error; possible causes include:
  - Invalid flag syntax
  - Unrecognized flags
  - Invalid flag arguments
  - File I/O errors
  - Host vs. target architecture mismatch
  If you encounter an error missing from this list, please file an issue or a PR!', /Users/marc/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.53.3/src/ir/context.rs:573:15
```
Bindgen 0.58.1 (and possibly earlier versions) does allow this project to build and run successfully on M1.